[package]
name = "cama"
description = "HTTP server for Mesa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesa = { path = "../mesa" }
# mesa = "0.17.2"
directories = "4.0.1" # XDG Base Directory Specification
config = { version = "0.13.2", features = ["toml"] } # used to read manta configuration file
axum = { version = "0.6.15", features = ["headers", "ws", "macros"] }
jsonwebtoken = "8.1.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
tokio-util = "0.7.4"
tokio = { version = "1", features = ["full"] }
bytes = "1.4.0"
hyper = { version = "0.14.22", features = ["full"] }
tower = "0.4.13"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
base64 = "0.13.1"
tower-http = { version = "0.4.0", features = ["fs", "trace", "cors"] }
futures-util = { versoin = "0.3.28", default-features = false, features = ["sink", "std"] }
